CREATE TABLE public."Instructors" (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"LastName" text NULL,
	"FirstName" text NULL,
	CONSTRAINT "PK_Instructors" PRIMARY KEY (id)
);

CREATE TABLE public."Courses" (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"Title" text NULL,
	CONSTRAINT "PK_Courses" PRIMARY KEY (id)
);

CREATE TABLE public."CourseInstructor" (
	"Coursesid" int4 NOT NULL,
	"Instructorsid" int4 NOT NULL,
	CONSTRAINT "PK_CourseInstructor" PRIMARY KEY ("Coursesid","Instructorsid")
);

ALTER TABLE public."CourseInstructor" ADD CONSTRAINT "FK_CourseInstructor_Courses_Coursesid" 
FOREIGN KEY ("Coursesid") REFERENCES "Courses"(id) ON DELETE CASCADE;

ALTER TABLE public."CourseInstructor" ADD CONSTRAINT "FK_CourseInstructor_Instructors_Instructorsid" 
FOREIGN KEY ("Instructorsid") REFERENCES "Instructors"(id) ON DELETE CASCADE;

CREATE TABLE public."OfficeAssignments" (
	"InstructorID" int4 NOT NULL,
	"Location" varchar(50) NULL,
	CONSTRAINT "PK_OfficeAssignments" PRIMARY KEY ("InstructorID")
);

ALTER TABLE public."OfficeAssignments" ADD CONSTRAINT "FK_OfficeAssignments_Instructors_InstructorID" 
FOREIGN KEY ("InstructorID") REFERENCES public."Instructors"(id) ON DELETE CASCADE;
